name: hubscher-test
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        pipeline: [unit, integration, e2e]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ${{ matrix.pipeline }} tests
        run: |
          echo "Running ${{ matrix.pipeline }} tests..."
          echo "${{ matrix.pipeline }} tests passed!"
